### ISSUE TITLE
Bugfixes Client Intake View

### ISSUE THREAD

**Issue by BridgerJones** [epfirms/epfirms-web#103]
- [x] Move begin button to the left on mobile view
- [x] Implement Progress bar on the mobile view
- [x] Form is not scrollable
- [x] Add more guidance 
- [x] Add More direction in the beginning of the form where it focuses on the Client -> Spouse -> Children and then end in the general form for adding other members.
- [x] Add a section for just life insurance with policy type and death benefit and beneficiaries

**Comment by BridgerJones** [comment]
Double check with taylor on the progress bar. It doesn't really fit well on mobile.

**Comment by BridgerJones** [comment]
@tawillin mobile progress bar

**Comment by BridgerJones** [comment]
https://user-images.githubusercontent.com/36865056/163431819-5a59199c-032e-4bd0-ab46-8718797b3b80.mov
<img width="781" alt="Screen Shot 2022-04-14 at 11 21 06 AM" src="https://user-images.githubusercontent.com/36865056/163431850-8930e1d4-a2a6-4885-b3ea-57d405b33a22.png">


@tawillin Hey Taylor, What was the strength or idea behind separating out the flow of the intake? I do like the guided feeling of the forms with the questions in between, but it makes it really complex when adding "minor children" or "adult children" or "step children" versus just having a drop down. What do you think?

**Comment by BridgerJones** [comment]
I included a video and screenshot on that last one.

**Comment by tawillin** [comment]
The purpose of the separating adult children and minor children was to
simplify the form. Adult children need to collect their phone numbers and
addresses and email email. But minor children you just need their name.
Maybe we just need to ask for a birthday.
