### ISSUE TITLE
Appointees Redux

### ISSUE THREAD

**Issue by BridgerJones** [epfirms/epfirms-web#138]
- [x] make the rank assume 1-4 starting from the top
- [x] if spouse, they will be the assumed top appointee
- [x] executor can be selected from someone they have already added to their profile (or they can just enter right away)
- [ ] assume that the appointees will be the same from executor however allow the flexibility to change stuff down the form
- [x] after the continue, make it go to the spouse and make it exactly the same

**Comment by BridgerJones** [comment]
@tawillin Hey I am running into a bit of an issue with the design here. The issue is that in order to store a record of an appointee in our DB, there needs to be a user profile. If you want to be able to custom enter someone that has not already been added previously in the personal information, we would need to collect all of the information: first_name, last_name, address, city, state, zip, phone, etc.... 

There are two solutions to this:
1. When you add another row for an appointee, it has a popup that lets you decide to select a fam member, or fill out a form for the new appointee. This is the more robust and extensible solution. 
2. I could make it so there is a separate record in the database that just keeps a record of 4 entries for each type of appointee. Then we would not need to create a user profile for someone that has not already been added. In the long run, this solution is not the best because it does not expand very well and would not grow with the application. 

The other option is to do a card design similar to how personal information looks. 
It would look similar to this except that you would select the appointee type? I can still make it assume and generate everything. 
<img width="1421" alt="Screen Shot 2022-04-28 at 4 26 53 PM" src="https://user-images.githubusercontent.com/36865056/165848668-4cc34ef2-52fa-45ba-8066-a9b5990e7842.png">


<img width="1482" alt="Screen Shot 2022-04-28 at 4 10 04 PM" src="https://user-images.githubusercontent.com/36865056/165847848-5ceb8fc6-5157-4e2f-9555-5a3c5053c83e.png">

**Comment by tawillin** [comment]
Do the second option.

**Comment by BridgerJones** [comment]
- [x] make a combobox
- [x] make another page for spouse appointees
- [ ] copy the stuff from the client to spouse replacing client as 1 appointee
