### ISSUE TITLE
Life Insurance

### ISSUE THREAD

**Issue by BridgerJones** [epfirms/epfirms-web#159]
We need to collect the life insurance policy from the client. This data will be used to make an estimate of life insurance need.

Taylor's UI : https://play.tailwindcss.com/Z19NZFksYR

**Comment by BridgerJones** [comment]
DB Changes

```
ALTER TABLE `epfirms-dev`.`finanacial_summary` 
ADD COLUMN `total_term_death_benefit` FLOAT NULL AFTER `updated_at`,
ADD COLUMN `total_term_cash_value` FLOAT NULL AFTER `total_term_death_benefit`,
ADD COLUMN `total_term_surrender_value` FLOAT NULL AFTER `total_term_cash_value`,
ADD COLUMN `total_life_death_benefit` FLOAT NULL AFTER `total_term_surrender_value`,
ADD COLUMN `total_life_cash_value` FLOAT NULL AFTER `total_life_death_benefit`,
ADD COLUMN `total_life_surrender_value` FLOAT NULL AFTER `total_life_cash_value`,
ADD COLUMN `total_index_death_benefit` FLOAT NULL AFTER `total_life_surrender_value`,
ADD COLUMN `total_index_cash_value` FLOAT NULL AFTER `total_index_death_benefit`,
ADD COLUMN `total_index_surrender_value` FLOAT NULL AFTER `total_index_cash_value`,
ADD COLUMN `total_other_death_benefit` FLOAT NULL AFTER `total_index_surrender_value`,
ADD COLUMN `total_other_cash_value` FLOAT NULL AFTER `total_other_death_benefit`,
ADD COLUMN `total_other_surrender_value` FLOAT NULL AFTER `total_other_cash_value`;
```

**Comment by BridgerJones** [comment]
@tawillin Hey I am almost done with the life insurance component. Which things are considered countable, non countable, and unprotected. I have in my notes that the death benefit is uncountable. What about unprotected? etc

<img width="1404" alt="Screen Shot 2022-05-03 at 3 40 14 PM" src="https://user-images.githubusercontent.com/36865056/166562396-a5813f7a-d122-47bb-a6cc-aeb18485145d.png">

**Comment by tawillin** [comment]
Death benefit is noncountible everything else countible

**Comment by BridgerJones** [comment]
@tawillin so nothing is unprotected and I should remove that?
